# Generated by Django 5.0 on 2026-04-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=650)),
                ('description', models.CharField(max_length=650)),
                ('to_article_link', models.CharField(max_length=650)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=650)),
                ('certificate_image', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=650)),
                ('linkedin', models.CharField(max_length=650)),
                ('github', models.CharField(max_length=650)),
                ('phone', models.CharField(max_length=650)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended_university', models.CharField(max_length=650)),
                ('attended_college', models.CharField(max_length=650)),
                ('pursuing_degree', models.CharField(blank=True, max_length=650, null=True)),
                ('relevant_courses', models.CharField(blank=True, max_length=650, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=650)),
                ('what_have_you_done', models.CharField(max_length=650)),
            ],
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('name', models.CharField(default='Kirubel Moges', max_length=50)),
                ('career', models.CharField(default='Software Developer', max_length=50)),
                ('role', models.CharField(blank=True, max_length=600, null=True)),
                ('about_me', models.CharField(blank=True, max_length=600, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Last',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright', models.CharField(max_length=650)),
                ('logo_social_links', models.CharField(max_length=650)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=650)),
                ('description', models.CharField(max_length=650)),
                ('tools_used', models.CharField(max_length=600)),
                ('github_link', models.CharField(max_length=650)),
                ('url', models.CharField(max_length=650)),
                ('screenshots', models.FileField(blank=True, null=True, upload_to='projects/')),
                ('video', models.FileField(blank=True, null=True, upload_to='projects/')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=650)),
                ('framework', models.CharField(max_length=650)),
                ('tools', models.CharField(max_length=600)),
            ],
        ),
    ]
