# Generated by Django 5.0 on 2026-04-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirubel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_link',
            field=models.URLField(blank=True, max_length=650, null=True),
        ),
        migrations.AddField(
            model_name='introduction',
            name='imagebackground',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
