# Generated by Django 5.0 on 2026-06-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirubel', '0002_certificate_certificate_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='career',
            field=models.CharField(default='Software Developer', max_length=500),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='name',
            field=models.CharField(default='Kirubel Moges', max_length=500),
        ),
    ]
