# Generated by Django 5.0 on 2026-06-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirubel', '0003_alter_introduction_career_alter_introduction_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_name', models.CharField(default='Resume', max_length=650)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv/')),
            ],
        ),
    ]
