# Generated by Django 5.0 on 2026-06-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirubel', '0004_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='github_link',
            field=models.CharField(blank=True, max_length=650, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='url',
            field=models.CharField(blank=True, max_length=650, null=True),
        ),
    ]
