# Generated by Django 4.2 on 2026-06-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirubel', '0005_alter_projects_github_link_alter_projects_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_image_url',
            field=models.URLField(blank=True, max_length=650, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='cv_url',
            field=models.URLField(blank=True, max_length=650, null=True),
        ),
        migrations.AddField(
            model_name='introduction',
            name='image_url',
            field=models.URLField(blank=True, max_length=650, null=True),
        ),
        migrations.AddField(
            model_name='introduction',
            name='imagebackground_url',
            field=models.URLField(blank=True, max_length=650, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='screenshots_url',
            field=models.URLField(blank=True, max_length=650, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='video_url',
            field=models.URLField(blank=True, max_length=650, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='cv_file_url',
            field=models.URLField(blank=True, max_length=650, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_file_url',
            field=models.URLField(blank=True, max_length=650, null=True),
        ),
    ]
